title: Robotics Portfolio
# description: This is a Cycloidal QDD Actuator Project Page
theme: minima
description: >-
  Here is my portfolio

header_pages:
  - README.md
  - qdd-actuator.md
  - about.md