title: Robotics Portfolio
author: SeoJin Jeong
email: pysuk88@gmail.com
description: >-
  Robotics Engineer Portfolio - Design, Control Theory, Open Source Projects.
url: "https://jeongseojin.github.io"

header_pages:
  - README.md
  - qdd-actuator.md
  - about.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap