title: Robotics Portfolio
author: SeoJin Jeong
thema: minima
description: >-
  This is a Cycloidal QDD Actuator Project.
url: "https://jeongseojin.github.io"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap