title: Robotics Portfolio
thema: minima
description: >-
  This is a Cycloidal QDD Actuator Project.
url: "https://jeongseojin.github.io/quasi-direct-drive-actuator/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap